version: '3.3'

services:
  workspace:
    build: .
    tty: true
    working_dir: /home/vscode/workspace
    volumes:
      - ~/.ssh/:/home/vscode/.ssh/
      - ..:/home/vscode/workspace
      - ../../mods:/mods
      - ../../assets:/assets
    environment:
      - OLLAMA_SERVER_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.1:8b-instruct-q4_0
      - LOG_LEVEL=DEBUG
  # ollama:
  #   build:
  #     context: ./ollama
  #   environment:
  #     - MODEL_NAME=llama3.1:8b-instruct-q4_0
  #   volumes:
  #     - ollama:/root/.ollama
    
volumes:
  ollama: